# Generated by Django 4.0.4 on 2022-12-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
                ('people', models.IntegerField(choices=[(0, 'Wszyscy'), (1, 'Hubert F.'), (2, 'Karolina Ż.'), (3, 'Adam S.'), (4, 'Agata F.'), (5, 'Ola B.'), (6, 'Bartek Ś.'), (7, 'Filip H.'), (8, 'Gosia W.'), (9, 'Karolina K.'), (10, 'Kinga K.'), (11, 'Krzysztof B.'), (12, 'Kuba P.'), (13, 'Maks K.'), (14, 'Mateusz Z.'), (15, 'Patryk D.'), (16, 'Wiola S.')], default=0)),
            ],
        ),
    ]
